name: Daily Draw

on:
  schedule:
    - cron: "00 12 * * 1-5"  # 09:00 BRT
  workflow_dispatch:

# Secrets necessários:
#   SLACK_WEBHOOK_URL_PLUS_CANAIS
#   SLACK_WEBHOOK_URL_PLUS_EI

jobs:

  sorteio-lms:
    name: Draw - Canais
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pick and post (LMS)
        run: |
          chmod +x sorteio.sh
          SORTEADO=$(./sorteio.sh teams/team-plus-canais.txt)
          curl -s -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\":alarm_clock: Daily: hoje quem puxa é *$SORTEADO*!\"}" \
            "$SLACK_WEBHOOK_URL_PLUS_CANAIS"
        env:
          SLACK_WEBHOOK_URL_PLUS_CANAIS: ${{ secrets.SLACK_WEBHOOK_URL_PLUS_CANAIS }}

  sorteio-admin:
    name: Draw - EI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pick and post (Admin)
        run: |
          chmod +x sorteio.sh
          SORTEADO=$(./sorteio.sh teams/team-plus-ei.txt)
          curl -s -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\":alarm_clock: Daily: hoje quem puxa é *$SORTEADO*!\"}" \
            "$SLACK_WEBHOOK_URL_PLUS_EI"
        env:
          SLACK_WEBHOOK_URL_PLUS_EI: ${{ secrets.SLACK_WEBHOOK_URL_PLUS_EI }}
